In [8]:
import tensorflow as tf

In [9]:
tf.__version__

'2.8.0'

In [10]:
from sklearn.datasets import load_breast_cancer

In [19]:
df=load_breast_cancer()

In [20]:
type(df)

sklearn.utils.Bunch

In [21]:
df

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [24]:
df.data.shape

(569, 30)

In [25]:
df.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [29]:
df.frame

In [30]:
df.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [31]:
df.target_names

array(['malignant', 'benign'], dtype='<U9')

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
import sklearn.model_selection.train_test_split

ModuleNotFoundError: No module named 'sklearn.model_selection.train_test_split'

In [34]:
df.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [35]:
X_train,X_test,Y_train,Y_test=train_test_split(df.data,df.target,test_size=0.33)

In [36]:
X_train.shape

(381, 30)

In [37]:
N,D=X_train.shape

In [38]:
#N = no. of Rows
#D = no. of Columns

In [39]:
N

381

In [40]:
D

30

In [41]:
#Scale the data
from sklearn.preprocessing import StandardScaler

In [47]:
scaler=StandardScaler

In [44]:
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

TypeError: fit_transform() missing 1 required positional argument: 'X'

In [48]:
scaler=StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [49]:
X_train

array([[ 0.19880946, -0.68977582,  0.23560392, ...,  0.39770763,
        -0.47577432, -0.32647632],
       [-0.52094746, -0.68507499, -0.42395813, ...,  0.27285584,
         0.56323133,  1.05676502],
       [-1.36754455,  0.61470443, -1.3638242 , ..., -1.40046643,
        -0.72701594, -0.53496174],
       ...,
       [ 1.2091852 ,  0.62175568,  1.18650869, ...,  0.83700097,
         0.20014667, -0.03751337],
       [-0.58884905, -0.96712477, -0.61476987, ..., -0.9392855 ,
        -0.36068945, -0.2281749 ],
       [ 0.01411712,  0.10466441,  0.03454197, ...,  0.61658361,
        -0.26829737,  0.52366888]])

In [50]:
X_test

array([[-1.33169251,  0.39611585, -1.3204579 , ..., -0.79115887,
        -0.00895119,  0.44697218],
       [-0.37156395,  0.58649945, -0.24063694, ...,  1.37956677,
         2.42241929,  1.26200973],
       [ 0.60621903,  2.05785916,  0.57938044, ...,  0.39000073,
        -1.0787542 , -0.30433149],
       ...,
       [-0.44761373, -0.38892272, -0.49768085, ..., -1.23892979,
        -1.16466262, -1.2738427 ],
       [ 0.29658775, -1.74746251,  0.35072175, ...,  1.0204252 ,
         0.53891763,  0.92713678],
       [ 1.60844658, -1.17161087,  1.63594129, ...,  0.70906642,
        -0.8421008 , -0.3810282 ]])

In [51]:
#Building a model

In [55]:
#way 1

In [54]:
model=tf.keras.models.Sequential([tf.keras.Input(shape=(D,)),tf.keras.layers.Dense(1,activation='sigmoid')])

In [56]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [57]:
r=model.fit(X_train,Y_train,validation_data=(X_test,Y_test),epochs=100)

Epoch 1/100
12/12 [==============================] - 4s 81ms/step - loss: 1.3214 - accuracy: 0.1549 - val_loss: 1.1868 - val_accuracy: 0.1489
Epoch 2/100
12/12 [==============================] - 0s 9ms/step - loss: 1.2039 - accuracy: 0.1837 - val_loss: 1.0809 - val_accuracy: 0.1755
Epoch 3/100
12/12 [==============================] - 0s 8ms/step - loss: 1.0930 - accuracy: 0.2231 - val_loss: 0.9851 - val_accuracy: 0.2394
Epoch 4/100
12/12 [==============================] - 0s 8ms/step - loss: 0.9946 - accuracy: 0.2651 - val_loss: 0.8978 - val_accuracy: 0.2926
Epoch 5/100
12/12 [==============================] - 0s 8ms/step - loss: 0.9088 - accuracy: 0.3228 - val_loss: 0.8186 - val_accuracy: 0.3777
Epoch 6/100
12/12 [==============================] - 0s 8ms/step - loss: 0.8267 - accuracy: 0.3885 - val_loss: 0.7526 - val_accuracy: 0.4734
Epoch 7/100
12/12 [==============================] - 0s 7ms/step - loss: 0.7588 - accuracy: 0.4751 - val_loss: 0.6944 - val_accuracy: 0.5426
Epoch 8/100


12/12 [==============================] - 0s 10ms/step - loss: 0.1669 - accuracy: 0.9528 - val_loss: 0.1740 - val_accuracy: 0.9415
Epoch 59/100
12/12 [==============================] - 0s 10ms/step - loss: 0.1649 - accuracy: 0.9554 - val_loss: 0.1721 - val_accuracy: 0.9415
Epoch 60/100
12/12 [==============================] - 0s 9ms/step - loss: 0.1629 - accuracy: 0.9554 - val_loss: 0.1704 - val_accuracy: 0.9415
Epoch 61/100
12/12 [==============================] - 0s 10ms/step - loss: 0.1611 - accuracy: 0.9580 - val_loss: 0.1686 - val_accuracy: 0.9415
Epoch 62/100
12/12 [==============================] - 0s 10ms/step - loss: 0.1593 - accuracy: 0.9580 - val_loss: 0.1670 - val_accuracy: 0.9415
Epoch 63/100
12/12 [==============================] - 0s 9ms/step - loss: 0.1575 - accuracy: 0.9554 - val_loss: 0.1654 - val_accuracy: 0.9468
Epoch 64/100
12/12 [==============================] - 0s 9ms/step - loss: 0.1558 - accuracy: 0.9554 - val_loss: 0.1638 - val_accuracy: 0.9468
Epoch 65/100
12

In [58]:
#way2

In [59]:
model=tf.keras.models.Sequential()

In [60]:
model.add(tf.keras.layers.Dense(1,input_shape=(D,),activation='sigmoid'))

In [61]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [62]:
r=model.fit(X_train,Y_train,validation_data=(X_test,Y_test),epochs=100)

Epoch 1/100
12/12 [==============================] - 1s 30ms/step - loss: 1.0224 - accuracy: 0.3281 - val_loss: 0.9011 - val_accuracy: 0.4043
Epoch 2/100
12/12 [==============================] - 0s 8ms/step - loss: 0.9281 - accuracy: 0.3963 - val_loss: 0.8217 - val_accuracy: 0.4787
Epoch 3/100
12/12 [==============================] - 0s 10ms/step - loss: 0.8464 - accuracy: 0.4934 - val_loss: 0.7489 - val_accuracy: 0.5479
Epoch 4/100
12/12 [==============================] - 0s 8ms/step - loss: 0.7706 - accuracy: 0.5486 - val_loss: 0.6860 - val_accuracy: 0.6223
Epoch 5/100
12/12 [==============================] - 0s 8ms/step - loss: 0.7066 - accuracy: 0.6194 - val_loss: 0.6301 - val_accuracy: 0.6809
Epoch 6/100
12/12 [==============================] - 0s 9ms/step - loss: 0.6480 - accuracy: 0.6850 - val_loss: 0.5831 - val_accuracy: 0.7128
Epoch 7/100
12/12 [==============================] - 0s 9ms/step - loss: 0.5995 - accuracy: 0.7139 - val_loss: 0.5414 - val_accuracy: 0.7447
Epoch 8/100

12/12 [==============================] - 0s 7ms/step - loss: 0.1422 - accuracy: 0.9790 - val_loss: 0.1463 - val_accuracy: 0.9628
Epoch 59/100
12/12 [==============================] - 0s 8ms/step - loss: 0.1407 - accuracy: 0.9790 - val_loss: 0.1451 - val_accuracy: 0.9628
Epoch 60/100
12/12 [==============================] - 0s 8ms/step - loss: 0.1393 - accuracy: 0.9790 - val_loss: 0.1438 - val_accuracy: 0.9628
Epoch 61/100
12/12 [==============================] - 0s 8ms/step - loss: 0.1378 - accuracy: 0.9790 - val_loss: 0.1425 - val_accuracy: 0.9628
Epoch 62/100
12/12 [==============================] - 0s 8ms/step - loss: 0.1365 - accuracy: 0.9790 - val_loss: 0.1413 - val_accuracy: 0.9681
Epoch 63/100
12/12 [==============================] - 0s 8ms/step - loss: 0.1352 - accuracy: 0.9790 - val_loss: 0.1401 - val_accuracy: 0.9681
Epoch 64/100
12/12 [==============================] - 0s 7ms/step - loss: 0.1338 - accuracy: 0.9790 - val_loss: 0.1390 - val_accuracy: 0.9681
Epoch 65/100
12/12 

In [63]:
#Evaluate the model

In [64]:
print("Train score: ",model.evaluate(X_train,Y_train))
print("Test score: ",model.evaluate(X_test,Y_test))

12/12 [==============================] - 0s 2ms/step - loss: 0.1030 - accuracy: 0.9790
Train score:  [0.10304935276508331, 0.9790025949478149]
6/6 [==============================] - 0s 5ms/step - loss: 0.1129 - accuracy: 0.9734
Test score:  [0.1129073053598404, 0.9734042286872864]


In [65]:
import matplotlib.pyplot as plt

In [66]:
#plot what's written by the model

In [68]:
plt.plot(r.history['loss'],label='loss')
plt.plot(r.history['val_loss'],label='val_loss')
plt.title("Loss and Val_loss VS Iteration",loc='center')
plt.xlabel("Loss and Val_loss")
plt.ylabel("Iteration")
plt.legend()

In [69]:
plt.plot(r.history['accuracy'],label='accuracy')
plt.plot(r.history['val_accuracy'],label='val_accuracy')
plt.title("accuracy and val_accuracy VS Iteration",loc='center')
plt.xlabel("Accuracy and Val_accuracy")
plt.ylabel("Iteration")
plt.legend()

In [70]:
#Making prediction

In [71]:
Y_pred=model.predict(X_test)

In [72]:
print(Y_pred)

[[9.81976211e-01]
 [3.71963084e-02]
 [1.30074829e-01]
 [2.90454626e-01]
 [9.96343493e-01]
 [9.90020633e-01]
 [2.37963200e-01]
 [9.96821225e-01]
 [9.65295613e-01]
 [5.59412599e-01]
 [9.99481440e-01]
 [9.97746706e-01]
 [4.95064378e-01]
 [9.98006225e-01]
 [9.45299625e-01]
 [9.51660335e-01]
 [4.80045438e-01]
 [9.99835074e-01]
 [9.79410112e-01]
 [3.66246700e-02]
 [9.52106714e-03]
 [9.79433954e-01]
 [7.41368532e-03]
 [9.98599052e-01]
 [7.11841881e-02]
 [9.86606538e-01]
 [9.24563468e-01]
 [4.77081537e-03]
 [9.79650855e-01]
 [8.56807232e-01]
 [5.81630170e-01]
 [4.77960795e-01]
 [3.11926007e-03]
 [3.35784853e-02]
 [1.06352448e-01]
 [6.43021405e-01]
 [9.69193697e-01]
 [7.86453962e-01]
 [2.55137638e-06]
 [3.55462134e-02]
 [9.19340491e-01]
 [9.11791146e-01]
 [1.01585807e-04]
 [3.58512342e-01]
 [9.04053092e-01]
 [6.11785054e-03]
 [8.12020957e-01]
 [2.22821534e-02]
 [5.97691655e-01]
 [9.95042801e-01]
 [9.99009609e-01]
 [9.06487882e-01]
 [9.80245113e-01]
 [8.44465494e-01]
 [9.08063173e-01]
 [9.940790

In [76]:
import numpy as np
print(np.round(Y_pred))

[[1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.

In [75]:
round(45.54577)

46

In [79]:
np.round(Y_pred).flatten()

array([1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0.,
       1., 1., 0., 0., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0.,
       0., 1., 1., 1., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       0., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0.,
       1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0., 0.,
       0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0.,
       0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 0.,
       0.], dtype=float32)

In [80]:
#Calculating the accuracy, compare it to evaluate() output

In [82]:
print("manually calculate accuracy",np.mean(Y_pred==Y_test))

manually calculate accuracy 0.0


In [83]:
Y_pred

array([[9.81976211e-01],
       [3.71963084e-02],
       [1.30074829e-01],
       [2.90454626e-01],
       [9.96343493e-01],
       [9.90020633e-01],
       [2.37963200e-01],
       [9.96821225e-01],
       [9.65295613e-01],
       [5.59412599e-01],
       [9.99481440e-01],
       [9.97746706e-01],
       [4.95064378e-01],
       [9.98006225e-01],
       [9.45299625e-01],
       [9.51660335e-01],
       [4.80045438e-01],
       [9.99835074e-01],
       [9.79410112e-01],
       [3.66246700e-02],
       [9.52106714e-03],
       [9.79433954e-01],
       [7.41368532e-03],
       [9.98599052e-01],
       [7.11841881e-02],
       [9.86606538e-01],
       [9.24563468e-01],
       [4.77081537e-03],
       [9.79650855e-01],
       [8.56807232e-01],
       [5.81630170e-01],
       [4.77960795e-01],
       [3.11926007e-03],
       [3.35784853e-02],
       [1.06352448e-01],
       [6.43021405e-01],
       [9.69193697e-01],
       [7.86453962e-01],
       [2.55137638e-06],
       [3.55462134e-02],


In [84]:
y_pred=np.round(Y_pred)

In [85]:
y_pred

array([[1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],

In [86]:
print("manually calculate accuracy",np.mean(y_pred==Y_test))

manually calculate accuracy 0.5561339972838388


In [87]:
print("Evaluate Output",model.evaluate(X_test,Y_test))

6/6 [==============================] - 0s 8ms/step - loss: 0.1129 - accuracy: 0.9734
Evaluate Output [0.1129073053598404, 0.9734042286872864]


In [88]:
#Saving and loading a model

In [89]:
model.save("Linear Classifier")

INFO:tensorflow:Assets written to: Linear Classifier\assets
